#Expyriment 0.10.0 (Python 3.8.3), .xpe-file, coding: UTF-8
#date: Tue May 11 2021 22:36:45
#sha1: 755d7f
#modules: 
#display: size=(1440, 900), window_mode=False, open_gl=False
#os: uname_result(system='Darwin', node='Carunalnik.local', release='20.2.0', version='Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64', machine='x86_64', processor='i386')
Time,Type,Event,Value,Detail,Detail2
4543,Picture,loaded,/Users/blazistenic/Documents/Project/Multi-tasking/Stimuli/s2u.png
4551,Picture,loaded,/Users/blazistenic/Documents/Project/Multi-tasking/Stimuli/s2d.png
4559,Picture,loaded,/Users/blazistenic/Documents/Project/Multi-tasking/Stimuli/s3u.png
4559,stderr,received,'Traceback (most recent call last):'
4559,stderr,received,'  File "first_experiment.py", line 28, in <module>'
4560,stderr,received,'    exp_1.clock.wait(intertrial_interval) #intertrial interval'
4560,stderr,received,"NameError: name 'exp_1' is not defined"
